--- kernel-untouched/linux-3.19.0/arch/x86/kvm/Makefile	2015-02-08 18:54:22.000000000 -0800
+++ kernel-tlbsplit/linux-3.19.0/arch/x86/kvm/Makefile	2015-12-29 19:33:26.414677909 -0800
@@ -14,6 +14,7 @@ kvm-$(CONFIG_KVM_ASYNC_PF)	+= $(KVM)/asy
 kvm-y			+= x86.o mmu.o emulate.o i8259.o irq.o lapic.o \
 			   i8254.o ioapic.o irq_comm.o cpuid.o pmu.o
 kvm-$(CONFIG_KVM_DEVICE_ASSIGNMENT)	+= assigned-dev.o iommu.o
+kvm-y			+= tlbsplit.o
 kvm-intel-y		+= vmx.o
 kvm-amd-y		+= svm.o
 
